services:
  api_1:
    build: .
    environment:
      - INSTANCE_ID=app1
    restart: unless-stopped
  api_2:
    build: .
    environment:
      - INSTANCE_ID=app2
    restart: unless-stopped
  api_3:
    build: .
    environment:
      - INSTANCE_ID=app3
    restart: unless-stopped
  load_balancer:
    image: caddy:2.11-alpine
    volumes:
      - ./caddy_conf:/etc/caddy
      - ./caddy_data:/data
    ports:
      - 80:80
      - 443:443
  prometheus:
    image: prom/prometheus:main
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_conf:/etc/prometheus/
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password123
      - GF_SERVER_DOMAIN=api.battlecluster.com
      - GF_SERVER_ROOT_URL=https://api.battlecluster.com/dashboard
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
